sudo: false
language: python
python: 3.7

dist: xenial

services:
  - docker

install:
  - pip install tox

matrix:
  include:
    - stage: test
      python: 2.7
      env: TOX_ENV=py27
    - stage: test
      python: 3.4
      env: TOX_ENV=py34
    - stage: test
      python: 3.5
      env: TOX_ENV=py35
    - stage: test
      python: 3.6
      env: TOX_ENV=py36
    - stage: test
      python: 3.7
      env: TOX_ENV=py37
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: onefinestay
        password:
          secure: L838z+MtH79Px67frLMPo1LP/FULLDDlx6SOgZ/Npg+NBAs8D+Yu2OGCSLxgaHUU7FqK0Gqp4NNQxM8yLD1mGPbtgyd/DYlL8ugDHu45QEx+7YI2tAwc6XOKba1PXqYZi33/aCDUe5LYcVKfoNqXaXZxt25eWwI1VjnH5KJdEpI=
        on:
          tags: true
          repo: nameko/nameko-sqlalchemy

script:
  - tox -e $TOX_ENV
